import os

from dotenv import load_dotenv

load_dotenv()

HTTPS_ENDPOINT_URL = os.environ["HTTPS_ENDPOINT_URL"]
ENDPOINT_GET_PLAYERS = f"{HTTPS_ENDPOINT_URL}/players"
ENDPOINT_GET_EVENTS = f"{HTTPS_ENDPOINT_URL}/events"
ENDPOINT_GET_CONFIG = f"{HTTPS_ENDPOINT_URL}/config"
ENDPOINT_POST_SNAPSHOT = f"{HTTPS_ENDPOINT_URL}/snapshot"
